/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module "vue" {
  export interface GlobalComponents {
    AppLink: (typeof import"./../components/AppLink/index.vue"")"
    default;
    "t;"
    ];
    AppMain: (typeof imp
    "./../layout/components/AppMain/index.vue";
    vu;
    "default";
    a;
    ult;
    "];;
    AvatarCropper: (typeof
    "./../components/AvatarCropper/index.vue";
    ex;
    "default";
    d;
    efault;
    "];;
    Breadcrumb: (type
    "./../components/Breadcrumb/index.vue";
    in;
    "default"
    );
    ["default"];
    Calender: (t
    "./../views/admin/home/components/Calender.vue";
    Ca;
    "default";
    e;
    "))[";
    default;
    "];;
    ChinaMap: "./../views/admin/home/components/ChinaMap.vue";
    ts;
    "default"
    .;
    vue;
    "))[";
    default;
    "];;
    Echar;
    "./../components/Echarts/index.vue"
    /
    E;
    "default";
    d;
    ex
    .
    vue;
    "))[";
    default;
    "];;
    E;
    "./../components/Editor/index.vue";
    en;
    "default"
    /;
    index
    .
    vue;
    "))[";
    default;
    "];;
    "element-plus/es";
    i;
    "ElAlert";
    e;
    ment
    -
    plus
    /
    es;
    "))[";
    ElAlert;
    "];;
    ElA;
    "element-plus/es";
    eo;
    "ElAutocomplete";
    t;
    -
    plus
    /
    es;
    "))[";
    ElAutocomplete;
    "];;
    "element-plus/es";
    ty;
    "ElAutoResizer";
    e;
    ment
    -
    plus
    /
    es;
    "))[";
    ElAutoResize;
    "element-plus/es": "ElAvatar";
    p;

    ort(

    "element-plus/es"
    ))
    ["ElAva"
    element
    -
    plus
    /
    es;
    "to";
    ElBacktop;
    "i;mport(";
    element
    -
    plus
    /
    es;
    "))[";
    E;
    "element-plus/es";
    lB;
    "ElBadge";
    p;
    eof;

    import(

    "element-plus/es"
    ))
    ["E"
    element
    -
    plus
    /
    es;
    "re";
    ElBreadcrumb;
    "o;f import(";
    element
    -
    plus
    /
    es;
    "))[";
    ElBread;
    "element-plus/es";
    ea;
    "ElBreadcrumbItem";
    f;

    import(

    "element-plus/es"
    ))
    [""
    element
    -
    plus
    /
    es;
    "];";
    ElButton;
    "t;on: (typeof import(";
    element;
    "element-plus/es";
    tt;
    "ElCard";
    ElCard: (typeof import("elemen"
    element
    -
    plus
    /
    es;
    "ar";
    ElCheckbox;
    "h;eckbox: (typeof import(";
    element
    -
    plus;
    "element-plus/es";
    x;
    "";
    ElCheckboxGroup;
    "G;roup: (typeof import(";
    elem;
    "element-plus/es";
    lC;
    "ElCol";
    G;
    roup;
    "];;
    ElCol: (typeof import("element-plus/es"));
    "ElColorPicker";
    E;
    lColorPicker: (typeof import("element"
    element
    -
    plus
    /
    es;
    "lo";
    ElConfigProvider;
    "o;nfigProvider: (typeof import(";
    ele;
    "element-plus/es";
    El;
    "ElDatePicker";
    ";];;
    ElDatePicker: (typeof import"element-plus/es"")"
    ElDescriptions;
    "];;;
    ElDescriptions: (typeof import("e"
    element
    -
    plus
    /
    es;
    "[";
    "ElDescriptionsItem";
    ElDescriptionsItem: (typeof
    "element-plus/es";
    lu;
    "ElDialog";
    l;
    DescriptionsItem;
    "];;
    ElDial;
    "element-plus/es";

    t(

    "ElDivider";
    u;
    s
    /
    es;
    "))[";
    ElDialog;
    "];;
    ElDi;
    "element-plus/es";
    po;
    "ElDrawer";
    t;
    -
    plus
    /
    es;
    "))[";
    ElDivider;
    "];;
    E;
    "element-plus/es";
    im;
    "ElDropdown";
    t;
    -
    plus
    /
    es;
    "))[";
    ElDrawer;
    "];;
    ElDrop;
    "element-plus/es";
    or;
    "ElDropdownItem";
    e;
    s;
    "))[";
    ElDropdown;
    "];;
    ElDropdownI;
    "element-plus/es";
    rt;
    "ElDropdownMenu";
    s;
    "))[";
    ElDropdownItem;
    "];;
    E;
    "element-plus/es";
    yp;
    "ElEmpty";
    t;

    (

    "element-plus/es"
    ))
    ["ElDro"
    element
    -
    plus
    /
    es;
    "El";
    ElForm;
    "t;ypeof import(";
    element
    -
    plus
    /
    es;
    ")";
    element
    -
    plus
    /
    es;
    " E";
    ElFormItem;
    "o;f import(";
    element
    -
    plus
    /
    es;
    ")";
    element
    -
    plus
    /
    es;
    "El";
    ElIcon;
    ":; (typeof import(";
    element
    -
    plu;
    "element-plus/es";
    em;
    "ElImage";
    l;
    Icon: (typeof import("element-plus"
    element
    -
    plus
    /
    es;
    ";
    "ElImageViewer";
    p;
    eof;

    import(

    "element-plus/es";
    "element-plus/es";
    "ElInput";
    e;
    wer: (typeof import("element-plus/"
    element
    -
    plus
    /
    es;
    "we";
    ElInputNumber;
    "t;: (typeof import(";
    element
    -
    p;
    "element-plus/es";
    t;
    "";
    ElLink;
    "l;InputNumber: (typeof import";
    element
    -
    plus
    /
    es;
    ""
    )
    "ElMenu";
    u;
    tNumber;
    "];;
    ElLink: (typeof
    "element-plus/es";
    lu;
    "ElMenuItem";
    i;
    nk;
    "];;
    ElMenu: (typeof imp
    "element-plus/es"
    /
    e;
    "ElOption";
    n;
    u;
    "];;
    ElMenuItem: (typeof impo
    "element-plus/es";
    es;
    "ElPagination";
    m;
    "];;
    ElOption: (typeof impo
    "element-plus/es";
    es;
    "ElPopover";
    o;
    n;
    "];;
    ElPagination: (typeof
    "element-plus/es";
    lu;
    "ElProgress";
    a;
    gination;
    "];;
    ElPopover: ("element-plus/es"
    em;
    "ElRadio";
    e;
    s;
    "))[";
    ElPopover;
    "];;
    ElProgress;
    "element-plus/es";
    "e";
    ElRadioGroup;
    "";
    ))
    ["ElProgress"];
    ElRa;
    "element-plus/es";
    rt;
    "ElRow";
    n;
    t
    -
    plus
    /
    es;
    "))[";
    ElRadio;
    "];;
    ElR;
    "element-plus/es";
    f;
    "ElScrollbar";
    n;
    t
    -
    plus
    /
    es;
    "))[";
    ElRadioGroup;
    "];";
    element
    -
    plus
    /
    es;
    "of";
    ElSelect;
    "l;ement-plus/es"
    ))
    ["ElRow"];
    "element-plus/es";
    eo;
    "ElSkeleton";
    e;
    ment
    -
    plus
    /
    es;
    "))[";
    ElScrollbar;
    "];;
    "element-plus/es";
    f;
    "ElSkeletonItem";
    p;
    lus
    /
    es;
    "))[";
    ElSelect;
    "];;
    ElSke;
    "element-plus/es";
    po;
    "ElStatistic";
    l;
    us
    /
    es;
    "))[";
    ElSkeleton;
    "];;
    El;
    "element-plus/es";
    pe;
    "ElSubMenu";
    e;
    lement
    -
    plus
    /
    es;
    "))[";
    ElSkeleton;
    "element-plus/es";
    ti;
    "ElSwitch";
    e;
    of;

    import(

    "element-plus/es"
    )
    "element-plus/es";
    "ElTable";
    e;
    nu: (typeof import("element-plus/e"
    element
    -
    plus
    /
    es;
    ";;
    "ElTableColumn";
    t;
    ypeof;

    import(

    "element-plus/es";
    "element-plus/es";
    "ElTableV2";
    t;
    ypeof;

    import(

    "element-plus/es";
    "element-plus/es";
    "ElTabPane";
    m;
    n: (typeof import("element-"
    element
    -
    plus
    /
    es;
    "le";
    ElTabs;
    ";;;
    ElTableV2: (typeof im
    "element-plus/es";
    s
    /
    "ElTag";
    E;
    lTableV2;
    "];;
    ElTabPane: "element-plus/es";
    le;
    "ElText";
    s;
    /es"))["ElTabPane"];
    ElTab;

    "element-plus/es"(

    "";
    ElTooltip;
    "s;/es"
    ))
    ["ElTabs"];
    ElTag: (typ
    "element-plus/es";
    nt;
    "ElTreeSelect";
    l;
    Tag;
    "];;
    ElText: (typeof im
    "element-plus/es";
    s
    /
    "ElUpload";
    e;
    xt;
    "];;
    ElTooltip: (typeof imp
    "element-plus/es"
    /
    e;
    "ElWatermark";
    i;
    p;
    "];;
    ElTreeSelect: (typeof
    "./../components/Upload/FileUpload.vue";
    t;
    "";
    default;
    "U;pload: (typeof import(";
    element
    -
    pl;
    "./../components/GithubCorner/index.vue";
    ty;
    "default";
    r;

    t(

    "element-plus/es"
    ))
    ["ElWater".
    /../
    components
    /
    Hamburger
    /
    index
    .
    vue;
    "t(";
    default;
    "p;onents/Upload/FileUpload.vue"
    ))
    "./../components/IconSelect/index.vue";
    i;
    "default"
    .;./components/
    GithubCorner
    /
    index
    .
    v;
    "~icons/ep/arrow-down";
    Ha;

    "default"(;

    typeof;

    import(

    "./../components/"
    ~
    icons
    /
    ep
    /
    arrow
    -
    up;
    "))";
    default;
    "";
    ];
    IconSelect: (typeof i
    "~icons/ep/bell";
    on;
    "default";
    S;
    elect
    /
    index
    .
    vue;
    "))[";
    default;
    "];"
    ~
    icons
    /
    ep
    /
    bottom;
    " (";
    default;
    "p;ort("
    ~
    icons
    /
    ep
    /
    arrow
    -
    down;
    "))["
    ~
    icons
    /
    ep
    /
    close;
    "Ep";
    default;
    "(;typeof import("
    ~
    icons
    /
    ep
    /
    arr;
    "~icons/ep/lock";
    t;
    "";
    default;
    "p;Bell: (typeof import("
    ~
    icons
    /
    ep
    /
    bell;
    ")"
    ~
    icons
    /
    ep
    /
    question
    -
    filled;
    ": ";
    default;
    "m;port("
    ~
    icons
    /
    ep
    /
    bottom;
    "))[";
    "~icons/ep/top";
    IE;
    "default";
    t;
    ypeof;

    import(

    "~icons/ep/clos"
    ~
    icons
    /
    ep
    /
    user;
    ";
    "default";
    k;
    : (typeof import("~icons/ep/loc".
    /../
    components
    /
    LangSelect
    /
    index
    .
    vue;
    ": ";
    default;
    "m;port("
    ~
    icons
    /
    ep
    /
    question
    -
    filled;
    ")"
    ./../
    layout
    /
    components
    /
    Settings
    /
    components
    /
    LayoutSelect
    .
    vue;
    "ef";
    default;
    " ;  IEpUser: (typeof import("
    ~
    icons
    /
    ep
    /
    "./../components/Upload/MultiImageUpload.vue";
    mp;
    "default"
    /;
    components
    /
    LangSelect
    /
    index;
    "./../layout/components/NavBar/index.vue";
    pe;

    "default"(;

    "./../layout/components/Settings/"
    ./../
    layout
    /
    components
    /
    NavBar
    /
    components
    /
    NavbarAction
    .
    vue;
    "lo";
    default;
    "o;f import("
    ./../
    components
    /
    Upload;
    "./../components/CURD/PageContent.vue";

    "default"(;

    typeof;

    import(

    "./../layout/co"
    ./../
    components
    /
    CURD
    /
    PageForm
    .
    vue;
    "lt";
    default;
    "a;vbarAction: (typeof import("
    ./"./../components/
    CURD
    /
    PageModal
    .
    vue;
    "ts";
    default;
    "t;ion.vue"
    ))
    ["default"];
    Page;
    "./../components/CURD/PageSearch.vue";
    nt;
    "default";
    g;
    eContent
    .
    vue;
    "))[";
    default;
    "];;
    P;
    "./../components/RightToolbar/index.vue"
    /
    C;
    "default";
    o;
    rm
    .
    vue;
    "))[";
    default;
    "];;
    PageM;
    "vue-router";
    f;
    "RouterLink"
    /;
    components
    /
    CURD
    /
    PageModal
    .
    vue;
    ")";
    vue
    -
    router;
    ";;
    "RouterView";
    c;
    h: (typeof import("./../compo".
    /../
    layout
    /
    components
    /
    Settings
    /
    index
    .
    vue;
    "  ";
    default;
    "b;ar: (typeof import("
    ./../
    com;
    "./../layout/components/Sidebar/index.vue";
    "]";
    default;
    "t;erLink: (typeof import(";
    vue
    -
    rout;
    "./../layout/components/Sidebar/components/SidebarLogo.vue";
    ut;
    "default";
    u;
    terView;
    "];;
    Settings: (typeof
    "./../layout/components/Sidebar/components/SidebarMenu.vue";
    ul;
    "default";
    S;
    idebar: (typeof import("./../layout/".
    /../
    layout
    /
    components
    /
    Sidebar
    /
    components
    /
    SidebarMenuItem
    .
    vue;
    "yp";
    default;
    "t;("
    ./../
    layout
    /
    components
    /
    Sidebar
    /
    componen;
    "./../layout/components/Sidebar/components/SidebarMenuItemTitle.vue"
    /.
    "default";
    c;
    omponents
    /
    Sidebar
    /
    components
    /
    SidebarMe;
    "./../layout/components/Sidebar/components/SidebarMixTopMenu.vue";
    ay;
    "default";
    n;
    ents
    /
    Sidebar
    /
    components
    /
    SidebarMenuIte;

    "./../components/Upload/SingleImageUpload.vue"(

    "default";
    p;

    ort(

    "./../layout/components/Sid"
    ./../
    components
    /
    SizeSelect
    /
    index
    .
    vue;
    "ue";
    default;
    "u;lt"
    ];
    SidebarMixTopMenu: "./../components/SvgIcon/index.vue";
    en;
    "default";
    r;
    /components/
    SidebarMixTopMenu
    .
    vue;
    "))"
    ./../
    components
    /
    VeTable
    /
    TablePagination
    .
    vue;
    "mp";
    default;
    "/;components/Upload/SingleImage"
    ./../
    components
    /
    TagCloud
    /
    index
    .
    vue;
    "le";
    default;
    "o;f import("
    ./../
    components
    /
    Siz;
    "./../layout/components/TagsView/index.vue";
    n: "default";
    i;

    mport(

    "./../components/SvgIcon/index."
    ./../
    layout
    /
    components
    /
    Settings
    /
    components
    /
    ThemeColorPicker
    .
    vue;
    "on";
    default;
    "b;le/TablePagination.vue"
    ))
    "./../views/admin/system/role/components/tree.vue";
    mp;
    "default";
    g;
    Cloud
    /
    index
    .
    vue;
    "))[";
    default;
    "];;
    TagsView: (typeof import("./../layout/components/TagsView/index.vue"))["default"];
    ThemeColorPicker: (typeof import("./../layout/components/Settings/components/ThemeColorPicker.vue"))["default"];
    Tree: (typeof import("./../views/admin/system/role/components/tree.vue"))["default"];
  }
  export interface ComponentCustomProperties {
    vLoading: (typeof import("element-plus/es"))["ElLoadingDirective"];
  }
}
